### PR TITLE
Updated 16.04 installer

### PR DESCRIPTION
**Pull request by timgiles**
Hi. I have updated the 16.04 installer with the latest install instructions. I also changed the version that is installed to 2.5.6 as this is the version that we use. But it can of course be changed.

### CODE REVIEW

**Review by thenets — COMMENTED** [review]
Thanks Timothy. Looks good. Have you tested on a clean Ubuntu?

**Comment by timgiles** [comment]
Yes. Ubuntu 16.04.03 server, installed SSH, connected via putty, installed
EasyCKAN, ran the install.

I have also added a few plugins/extension scripts - so expect another pull
request tomorrow.

Regards.

**Comment by thenets** [comment]
Oh, ok, man! :)
I'll accept this pull request. Thanks for the contribution.
I'm working on the new version of EasyCKAN. This version will be compatible with any Linux distribution and will use Docker: https://github.com/thenets/Easy-CKAN/tree/dev

**Comment by thenets** [comment]
I've set the CKAN version to 2.6.3. But you can change it for your custom installation later.

**Pull request merged**
